core/apps/site_receitas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "site_receitas"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:receita_id>", views.receita, name="receita"),
    path("buscar", views.buscar, name="buscar"),
    path("criar/receita", views.criar_receita, name="criar_receita"),
    path("deleta/<int:receita_id>", views.deleta_receita, name="deleta_receita"),
    path("edita/<int:receita_id>", views.edita_receita, name="edita_receita"),
    path("atualiza_receita", views.atualiza_receita, name="atualiza_receita"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/apps/usuario/urls.py
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "usuario"

urlpatterns = [
    path("cadastro", views.cadastro, name="cadastro"),
    path("login", views.login, name="login"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("logout", views.logout, name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.apps.site_receitas.urls")),
    path("usuario/", include("core.apps.usuario.urls")),
]

core/apps/pessoas/models.py
from django.db import models


class Pessoa(models.Model):
    nome = models.CharField(null=False, blank=False, max_length=200)
    email = models.EmailField(null=False, blank=False)

    def __str__(self) -> str:
        return self.nome.title()

core/apps/site_receitas/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


class Receita(models.Model):
    nome_receita = models.CharField(max_length=200)
    ingredientes = models.TextField()
    modo_preparo = models.TextField()
    tempo_preparo = models.IntegerField()
    rendimento = models.CharField(max_length=100)
    categoria = models.CharField(max_length=100)
    date_receita = models.DateTimeField(default=datetime.now, blank=True)
    publicar = models.BooleanField(default=False)
    foto_receita = models.ImageField(upload_to='./fotos/%d/%m/%Y/', blank=True)

    pessoa = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.nome_receita.title()

core/apps/usuario/models.py
from django.db import models

# Create your models here.

core/apps/site_receitas/views.py
from core.apps.site_receitas.models import Receita
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect, render


def index(request):
    receitas = Receita.objects.order_by("-date_receita").filter(publicar=True).all()

    paginator = Paginator(receitas, 1)

    page = request.GET.get("page")

    receitas_por_pagina = paginator.get_page(page)
    
    dados = {"receitas": receitas_por_pagina}

    return render(request, "index.html", dados)


def receita(request, receita_id):
    receita = get_object_or_404(Receita, pk=receita_id)

    receita_a_exibir = {"receita": receita}
    return render(request, "receitas/receita.html", receita_a_exibir)


def buscar(request):

    receitas = Receita.objects.order_by("-date_receita").filter(publicar=True).all()

    if "search" in request.GET:
        termo_busca = request.GET["search"]
        if termo_busca:
            receitas = receitas.filter(nome_receita__contains=str(termo_busca).title())

    dados = {"receitas": receitas}

    return render(request, "receitas/buscar.html", dados)

def criar_receita(request):
    if request.method == "POST":

        user = get_object_or_404(User, pk=request.user.id)

        nome_receita = request.POST.get("nome_receita")
        ingredientes = request.POST.get("ingredientes")
        modo_preparo = request.POST.get("modo_preparo")
        tempo_preparo = request.POST.get("tempo_preparo")
        rendimento = request.POST.get("rendimento")
        categoria = request.POST.get("categoria")
        files = request.FILES.get("foto_receita")

        Receita.objects.create(
            nome_receita=nome_receita,
            ingredientes=ingredientes,
            modo_preparo=modo_preparo,
            tempo_preparo=tempo_preparo,
            rendimento=rendimento,
            categoria=categoria,
            foto_receita=files,
            pessoa=user,
        )
        return redirect("usuario:dashboard")

    return render(request, "receitas/criar_receita.html")


def deleta_receita(request, receita_id):
    with transaction.atomic():
        receita = get_object_or_404(Receita, pk=receita_id)

        receita.delete()

    return redirect("usuario:dashboard")


def edita_receita(request, receita_id):
    receita = get_object_or_404(Receita, pk=receita_id)

    receita_a_editar = {'receita': receita}

    return render(request, 'receitas/edita_receita.html', receita_a_editar)


def atualiza_receita(request):
    if request.method == 'POST':

        receita_id = request.POST.get('receita_id')
        with transaction.atomic():

            receita = get_object_or_404(Receita, pk=receita_id)

            receita.nome_receita = request.POST['nome_receita']
            receita.ingredientes = request.POST['ingredientes']
            receita.modo_preparo = request.POST['modo_preparo']
            receita.tempo_preparo = request.POST['tempo_preparo']
            receita.rendimento = request.POST['rendimento']
            receita.categoria = request.POST['categoria']

            if 'foto_receita' in request.FILES:
                receita.foto_receita = request.FILES['foto_receita']

            receita.save()
        return redirect("usuario:dashboard")

core/apps/usuario/views.py
import logging

from core.apps.site_receitas.models import Receita
from core.apps.usuario.serializers import LoginSerializer, UsuarioSerializer
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

clogger = logging.getLogger(__name__)


# Create your views here.
def login(request):
    if request.method == "POST":
        email = request.POST.get("email")
        senha = request.POST.get("senha")
        validacao = LoginSerializer().validate(
            {
                "email": email,
                "password": senha,
            }
        )
        if validacao:
            return redirect("usuario:login")

        user_name = (
            User.objects.filter(email=email).values_list(
                "username", flat=True).get()
        )

        user = authenticate(request, username=user_name, password=senha)

        if user is not None:
            auth.login(request, user)
            return redirect("usuario:dashboard")
    return render(request, "usuario/login.html")


def logout(request):
    auth.logout(request)
    return redirect("site_receitas:index")


def dashboard(request):
    if request.user.is_authenticated:
        receitas = Receita.objects.order_by("-date_receita").filter(
            pessoa=request.user.id
        )
        return render(request, "usuario/dashboard.html", {"receitas": receitas})
    else:
        return redirect("site_receitas:index")


def cadastro(request):
    if request.method == "POST":
        nome = request.POST.get("nome")
        email = request.POST.get("email")
        password = request.POST.get("password")
        password2 = request.POST.get("password2")

        validacao = UsuarioSerializer().validate(
            {"nome": nome, "email": email,
                "password": password, "password2": password2}
        )

        if validacao:
            return render(request, "usuario/cadastro.html")

        user = User.objects.create_user(
            username=nome, email=email, password=password)

        user.save()

        return redirect("usuario:login")
    else:
        return render(request, "usuario/cadastro.html")

core/apps/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Preloader -->
    <div id="preloader">
        <i class="circle-preloader"></i>
        <img src="{% static 'img/core-img/pizza.png' %}" alt="">
    </div>

    <!-- Search Wrapper -->
    {% include 'partials_html/busca.html' %}

    <!-- ##### Header Area Start ##### -->
    {% include 'partials_html/menu.html' %}
    <!-- ##### Header Area End ##### -->

    <!-- ##### Best Receipe Area Start ##### -->
    <section class="best-receipe-area">
        <div class="container">
            <div class="row">
                {% if receitas %}
                {% for receita in receitas %}
                <!-- Single Best Receipe Area -->
                <div class="col-12 col-sm-6 col-lg-4">
                    <div class="single-best-receipe-area mb-30">
                        {% if receita.foto_receita == null %}
                            <img src="{% static 'img/bg-img/foto_receita.png' %}" alt="">
                        {% else %}
                            <img src="{{ receita.foto_receita.url }}" alt="">
                        {% endif %}
                        <div class="receipe-content">
                            <a href="{% url 'site_receitas:receita' receita.id %}">
                                <h5>{{ receita.nome_receita }}</h5>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                {% endif %}
            </div>
        </div>
    </section>
    <!-- ##### Best Receipe Area End ##### -->
        <!-- ##### Pagination ##### -->
        <section class="top-catagory-area section-padding-20-0">
            <div class="container">
                {% if receitas.has_other_pages %}
                <ul class="pagination">                    
                    {% if receitas.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ receitas.previous_page_number }}" class="page-link">&laquo;</a>
                        {% else %}
                    <li class="page-item disabled">
                    </li>
                        <a class="page-link">&laquo;</a>
                    </li>
                {% endif %}
    
                {% for pagina in receitas.paginator.page_range  %}
                    {% if receitas.number == pagina  %}
                        <li class="page-item active">
                            <a class="page-link"></a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a href="?page={{ pagina }}" class="page-link">{{ pagina }}</a>
                        </li>

                    {% endif %}
                {% endfor %}
                    
    
                {% if receitas.has_next %}
                    <li class="page-item">
                        <a href="?page={{ receitas.next_page_number }}" class="page-link">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                    </li>
                {% endif %}                    
                </ul>
                {% endif %}
            </div>
        </section>
        <!-- ##### Pagination End ##### -->
    {% include 'partials_html/footer.html' %}
{% endblock  %}

core/apps/templates/partials_html/busca.html
{% load static %}
<div class="search-wrapper">
    <!-- Close Btn -->
    <div class="close-btn"><i class="fa fa-times" aria-hidden="true"></i></div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="{% url 'site_receitas:buscar' %}">
                    <input type="search" name="search" placeholder="O que está procurando...">
                    <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                </form>
            </div>
        </div>
    </div>
</div>

core/apps/templates/partials_html/footer.html
{% load static %}
<footer class="footer-area">
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-12 h-100 d-flex flex-wrap align-items-center justify-content-between">
                <!-- Footer Social Info -->
                <div class="footer-social-info text-right">
                    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                </div>
                <!-- Footer Logo -->
                <div class="footer-logo">
                    <a href="{% url 'site_receitas:index' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</footer>

core/apps/templates/partials_html/menu.html
{% load static %}
<header class="header-area">

    <!-- Top Header Area -->
    <div class="top-header-area">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-between">
                <!-- Breaking News -->
                <div class="col-12 col-sm-6">
                    <div class="breaking-news">
                        <div id="breakingNewsTicker" class="ticker">
                            <ul>
                                <li><a href="">Boas vindas!</a></li>
                                <li><a href="">As melhores receitas</a></li>
                                <li><a href="">Você encontra aqui!</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!-- Top Social Info -->
                <div class="col-12 col-sm-6">
                    <div class="top-social-info text-right">
                        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Navbar Area -->
    <div class="delicious-main-menu">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">
                <!-- Menu -->
                <nav class="classy-navbar justify-content-between" id="deliciousNav">

                    <!-- Logo -->
                    <a class="nav-brand" href="{% url 'site_receitas:index' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- close btn -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">
                            <ul>
                                {% if user.is_authenticated %}
                                    <li><a href="{% url 'site_receitas:index' %}">Página principal</a></li>                                
                                    <li><a href="{% url 'usuario:dashboard' %}">Minhas Receitas</a></li>                                
                                    <li><a href="{% url 'site_receitas:criar_receita' %}">Criar Receita</a></li>                                
                                    <li><a href="{% url 'usuario:logout' %}">Logout</a></li>                                
                                {% else %}
                                    <li><a href="{% url 'usuario:cadastro' %}">Cadastro</a></li>
                                    <li><a href="{% url 'usuario:login' %}">Login</a></li>
                                {% endif %}
                            </ul>

                            <!-- Newsletter Form -->
                            <div class="search-btn">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </div>

                        </div>
                        <!-- Nav End -->
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>

core/apps/templates/receitas/buscar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Preloader -->
    <div id="preloader">
        <i class="circle-preloader"></i>
        <img src="{% static 'img/core-img/pizza.png' %}" alt="">
    </div>

    <!-- Search Wrapper -->
    {% include 'partials_html/busca.html' %}

    <!-- ##### Header Area Start ##### -->
    {% include 'partials_html/menu.html' %}
    <!-- ##### Header Area End ##### -->

    <!-- ##### Best Receipe Area Start ##### -->
    <section class="best-receipe-area">
        <div class="container">
            <div class="row">
                {% if receitas %}
                {% for receita in receitas %}
                <!-- Single Best Receipe Area -->
                <div class="col-12 col-sm-6 col-lg-4">
                    <div class="single-best-receipe-area mb-30">
                        {% if receita.foto_receita == null %}
                            <img src="{% static 'img/bg-img/foto_receita.png' %}" alt="">
                        {% else %}
                            <img src="{{ receita.foto_receita.url }}" alt="">
                        {% endif %}
                        <div class="receipe-content">
                            <a href="{% url 'site_receitas:receita' receita.id %}">
                                <h5>{{ receita.nome_receita }}</h5>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                    <div class="col-12 col-sm-6 col-lg-4">
                        <p>Receita não encontrada.</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- ##### Best Receipe Area End ##### -->
{% endblock  %}

core/apps/templates/receitas/criar_receita.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Preloader -->
<div id="preloader">
   <i class="circle-preloader"></i>
   <img src="{% static 'img/core-img/pizza.png' %}" alt="">
</div>
 
{% include 'partials_html/busca.html' %}
 
{% include 'partials_html/menu.html' %}
 
<!-- ##### Contact Form Area Start ##### -->
<div class="contact-area section-padding-0-80">
   <div class="container">
       <div class="row">
           <div class="col-12">
               <div class="section-heading">
                   <h3>Crie sua receita, {{ user.username }} :)</h3>
               </div>
           </div>
       </div>
 
       <div class="row">
           <div class="col-12">
           <p>Todos os campos são obrigatórios</p>
               <div class="contact-form-area">
                   <form action="{% url 'site_receitas:criar_receita' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                       <div class="row">
                           <div class="col-12 col-lg-12">
                               <label for="nome_receita"><b>Título da receita</b></label>
                               <input type="text" id="nome_receita" class="form-control" name="nome_receita" placeholder="Ex. Suco de limão" required>
                           </div>
                           <div class="col-12">
                               <label for="file"><b>Ingredientes</b></label>
                               <textarea class="form-control" name="ingredientes" cols="30" rows="10" placeholder="Ex. 2 Limões &#10;200ml de água" required></textarea>
                           </div>
                           <div class="col-12">
                               <label for="file"><b>Modo de preparo</b></label>
                               <textarea class="form-control" name="modo_preparo" cols="30" rows="10" placeholder="Ex. Corte o limão com cuidado e exprema no copo  &#10;Misture com a água e sirva." required></textarea>
                           </div>
                           <div class="col-12 col-lg-3">
                               <label for="file"><b>Tempo de preparo (minutos)</b></label>
                               <input type="number" class="form-control" name="tempo_preparo" placeholder="Ex. 2" required>
                           </div>
                           <div class="col-12 col-lg-3">
                               <label for="file"><b>Rendimento</b></label>
                               <input type="text" class="form-control" name="rendimento" placeholder="Ex. serve 1 pessoa" required>
                           </div>
                           <div class="col-12 col-lg-3">
                               <label for="file"><b>Categoria da receita</b></label>
                               <input type="text" class="form-control" name="categoria" placeholder="Ex. Sucos e bebidas" required>
                           </div>
                           <div class="col-12 col-lg-3">
                               <label for="file"><b>Foto</b></label>
                               <input type="file" class="form-control" name="foto_receita" required>
                           </div>
                           <div class="col-12 text-center">
                               <button class="btn delicious-btn mt-30" type="submit">Criar sua receita</button>
                           </div>
                       </div>
                   </form>
               </div>
           </div>
       </div>
   </div>
</div>
 
{% include 'partials_html/footer.html' %}
{% endblock %}

core/apps/templates/receitas/edita_receita.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Preloader -->
<div id="preloader">
    <i class="circle-preloader"></i>
    <img src="{% static 'img/core-img/pizza.png' %}" alt="">
</div>

{% include 'partials_html/busca.html' %}

{% include 'partials_html/menu.html' %}

<!-- ##### Contact Form Area Start ##### -->
<div class="contact-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading">
                    <h3>Edite aqui sua receita, {{ user.username }} :)</h3>
                </div>
            </div>
        </div>
        {% include 'partials_html/alertas.html'%}
        <div class="row">
            <div class="col-12">
            <p>Todos os campos são obrigatórios</p>
                <div class="contact-form-area">
                    <form action="{% url 'site_receitas:atualiza_receita' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="text" id="receita_id" class="form-control" name="receita_id" value="{{receita.id}}" hidden>
                        <div class="row">
                            <div class="col-12 col-lg-12">
                                <label for="nome_receita"><b>Título da receita</b></label>
                                <input type="text" id="nome_receita" class="form-control" name="nome_receita" placeholder="Ex. Suco de limão" value="{{receita.nome_receita}}" required>
                            </div>
                            <div class="col-12">
                                <label for="file"><b>Ingredientes</b></label>
                                <textarea class="form-control" name="ingredientes" cols="30" rows="10" placeholder="Ex. 2 Limões &#10;200ml de água" required>{{receita.ingredientes}}</textarea>
                            </div>
                            <div class="col-12">
                                <label for="file"><b>Modo de preparo</b></label>
                                <textarea class="form-control" name="modo_preparo" cols="30" rows="10" placeholder="Ex. Corte o limão com cuidado e exprema no copo  &#10;Misture com a água e sirva." required>{{receita.modo_preparo}}</textarea>
                            </div>
                            <div class="col-12 col-lg-4">
                                <label for="file"><b>Tempo de preparo (minutos)</b></label>
                                <input type="number" class="form-control" name="tempo_preparo" placeholder="Ex. 2" value="{{receita.tempo_preparo}}" required>
                            </div>
                            <div class="col-12 col-lg-4">
                                <label for="file"><b>Rendimento</b></label>
                                <input type="text" class="form-control" name="rendimento" placeholder="Ex. serve 1 pessoa" value="{{receita.rendimento}}" required>
                            </div>
                            <div class="col-12 col-lg-4">
                                <label for="file"><b>Categoria da receita</b></label>
                                <input type="text" class="form-control" name="categoria" placeholder="Ex. Sucos e bebidas" value="{{receita.categoria}}"required>
                            </div>
                            <div class="col-12 col-lg-4">
                                <label for="file"><b>Foto utilizada</b></label>
                                <img src="{{ receita.foto_receita.url }}" alt="">
                            </div>
                            <div class="col-12 col-lg-4">
                                <label for="file"><b>Adicionar nova foto</b></label>
                                <input type="file" class="form-control" name="foto_receita">
                            </div>
                            <div class="col-12 text-center">
                                <button class="btn btn-success" type="submit">Atualizar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'partials_html/footer.html' %}
{% endblock %}

core/apps/templates/usuario/cadastro.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Preloader -->
<div id="preloader">
    <i class="circle-preloader"></i>
    <img src="{% static 'img/core-img/pizza.png' %}" alt="">
</div>

{% include 'partials_html/busca.html' %}

{% include 'partials_html/menu.html' %}

<!-- ##### Contact Form Area Start ##### -->
<div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading">
                    <h2>Criar conta</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="contact-form-area">
                    <form action="{% url  'usuario:cadastro' %}" method="POST">{% csrf_token %}
                        <div class="row">
                            <div class="col-12 col-lg-12">
                                <label for="nome_receita"><b>Nome completo</b></label>
                                <input type="text" class="form-control" name="nome" placeholder="Ex.:Guilherme Lima" required>
                            </div>
                            <div class="col-12 col-lg-12">
                                <label for="email"><b>Email</b></label>
                                <input type="email" class="form-control" name="email" placeholder="Ex.: guilherme@receitas.com" required>
                            </div>
                            <div class="col-12 col-lg-6">
                                <label for="password"><b>Senha</b></label>
                                <input type="password" class="form-control" name="password" placeholder="Digite sua senha" required>
                            </div>
                            <div class="col-12 col-lg-6">
                                <label for="password2"><b>Confirmação de senha</b></label>
                                <input type="password" class="form-control" name="password2" placeholder="Digite sua senha mais uma vez" required>
                            </div>
                            <div class="col-12 text-center">
                                <button class="btn btn-success" type="submit">Criar sua conta</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'partials_html/footer.html' %}
{% endblock %}

core/apps/templates/usuario/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Preloader -->
    <div id="preloader">
        <i class="circle-preloader"></i>
        <img src="{% static 'img/core-img/pizza.png' %}" alt="">
    </div>

    <!-- Search Wrapper -->
    {% include 'partials_html/busca.html' %}

    <!-- ##### Header Area Start ##### -->
    {% include 'partials_html/menu.html' %}
    <!-- ##### Header Area End ##### -->
    <div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading">
                    <h3>Olá, {{ user.username | title }}</h3>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- ##### Best Receipe Area Start ##### -->
    <section class="best-receipe-area">
        <div class="container">
            <div class="row">
                {% if receitas %}
                {% for receita in receitas %}
                <!-- Single Best Receipe Area -->
                <div class="col-12 col-sm-6 col-lg-4">
                    <div class="single-best-receipe-area mb-30">
                        {% if receita.foto_receita == null %}
                            <img src="{% static 'img/bg-img/foto_receita.png' %}" alt="">
                        {% else %}
                            <img src="{{ receita.foto_receita.url }}" alt="">
                        {% endif %}
                        <div class="receipe-content">
                            <a href="{% url 'site_receitas:receita' receita.id %}">
                                <h5>{{ receita.nome_receita }}</h5>
                                <a href="{% url 'site_receitas:deleta_receita' receita.id %}">
                                    <i class="fa fa-trash fa-7x" aria-hidden="true"></i>
                                </a>
                                <a href="{% url 'site_receitas:edita_receita' receita.id %}">
                                    <i class="fa fa-pencil fa-7x" aria-hidden="true"></i>
                                </a>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                {% endif %}
            </div>
        </div>
    </section>
    <!-- ##### Best Receipe Area End ##### -->
{% endblock  %}